### ISSUE TITLE
gnuplot directory

### ISSUE THREAD

**Issue by jccerrillo** [volkers/vgplot#2]
Hello,
Your library is very useful.
To be able to useit however, I have to redefine open-plot since gnuplot is in my /usr/local/bin directory.
It would be nice to have a settable parameter for the gnuplot directory.
all best,
jc

**Comment by volkers** [comment]
Hi jc,
I just added a variable `*gnuplot-binary*` which you could set according to your needs. I hope this solves your issue.
Regards
Volker

**Comment by jccerrillo** [comment]
Many thanks Volker,
jc
