### ISSUE TITLE
setting line color

### ISSUE THREAD

**Issue by bpostlethwaite** [volkers/vgplot#7]
Sorry if this is obvious, but I'm new to common lisp. How do I set the line color?

For example:

```lisp
(let* ((envelope (asr 0.01 10 0.1))
       (envsig (env-as-signal envelope 10)))
  (vgplot:plot envsig)
  (vgplot:format-plot t "set terminal qt")
  (vgplot:format-plot t "set object 1 rectangle from screen 0,0 to screen 1,1 fillcolor rgb '#121212' behind")
  (vgplot:axis '(t t t t)))
```

I'm setting a dark background and want to set `y` (here `envsig`) to a specific color? I couldn't see documentation on this other than for `bars`.

Many thanks.

**Comment by volkers** [comment]
No, this is not obvious at all. I thought it was easily doable by some format-plot commands but failed. So I added more colors in the plot command (white, yellow and magenta, maybe this solves your actual issue) but are still not satisfied.
I think about adding the full rgb string in the label. Another option would be a :color "color" parameter after the vectors, more like in the bar command. The latter would be more lispy.

**Comment by volkers** [comment]
Hi Ben,
I added a "#RRGGBB" color specification in the plot command, that should solve your issue.
Regards
Volker
