### ISSUE TITLE
Additional style setting in plot not working

### ISSUE THREAD

**Issue by anon00000000** [volkers/vgplot#8]
Hello, trying to use the additional style thing in `plot` fails here:
```
> (ql:quickload :vgplot)
> (setq vgplot:*debug* t)
> (setq x '(1 2 3))
> (setq y '(4 5 6))
> (vgplot:plot x y ";red;with linespoints")
set nologscale
set grid

plot "/home/developer/vgplot-ZRYB0DC0.dat" with lines  title "red"
```
any idea why?

**Comment by volkers** [comment]
I tried your code and it seems to work for me. I see lines and the points are marked with "+" signs:

CL-USER> (vgplot:plot x y ";red;with linespoints")
set nologscale
set grid

plot "/home/vos/vgplot-A2A7V6Y6.dat" with linespoints  title 'red'  

Strange!
Get you always the same result?
/Volker

**Comment by anon00000000** [comment]
Thanks for the fast answer and yes, whatever the additional style is ignored here. Using sbcl 2.1.8 on Ubuntu and `vgplot-20210807-git` according to Quicklisp.

I see a commit done October 8th that seems related to the label machinery; maybe I need it.

**Comment by anon00000000** [comment]
Apologies, it was indeed a stale Quicklisp problem! Sorry, I'm still a Lisp newbie.
