### ISSUE TITLE
Not plotting in SBCL + MS Windows

### ISSUE THREAD

**Issue by DeltaQH** [volkers/vgplot#9]
Hi

I am trying to use vgplot in windows 10 with SBCL lisp.

I Loaded vgplot using quicklisp but when executing a plto command, gnuplot program is not shown.

Gnuplot is installed and in windows PATH. I can call it directyl from a windows terminal (cmd)

**Run example:**
-------------------------------------------------------------------------------
SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
*  (load "~/quicklisp/setup.lisp")
T
* (ql:quickload "vgplot")
To load "vgplot":
  Load 1 ASDF system:
    vgplot
; Loading "vgplot"
..

(setf vgplot:*debug* t)
T

(vgplot:plot '(1 2 3) '(0 -2 17))
set nologscale
set grid

plot "C:/Users/alfae/vgplot-H4XHEQOS.dat" with lines  title ''
""
-------------------------------------------------------------

But gnuplot windows does not appear (gnuplot not called?)

Regards

**Comment by DeltaQH** [comment]
For info. 

Execution of the "run" above  in debian liniu on a virtual machine (VMWARE) hosted in windows 10 lpatop.... works without problem

**Comment by volkers** [comment]
Maybe a path problem? Can you run gnuplot directly from a command window?

**Comment by volkers** [comment]
OK, you have gnuplot in your path. Do you have write-permission in the folder where you call sbcl?
Do you get any failure message?

**Comment by volkers** [comment]
When you call gnuplot directly from cmd-prompt, do you get a plot window when running, e.g. load "all.dem"?:

 ```
       G N U P L O T
        Version 5.4 patchlevel 3    last modified 2021-12-24 

        Copyright (C) 1986-1993, 1998, 2004, 2007-2021
        Thomas Williams, Colin Kelley and many others

        gnuplot home:     http://www.gnuplot.info
        faq, bugs, etc:   type "help FAQ"
        immediate help:   type "help"  (plot window: hit 'h')

Terminal type is now 'windows'
Options are '0 color solid butt enhanced standalone'
gnuplot> load "all.dem"
******************** file simple.dem ********************
```

**Comment by DeltaQH** [comment]
> OK, you have gnuplot in your path. Do you have write-permission in the folder where you call sbcl? Do you get any failure message?

Yes I do have write-permission. I dont get any failure messages

> OK, you have gnuplot in your path. Do you have write-permission in the folder where you call sbcl? Do you get any failure message?

Didnt expext such a quick response to my questions ;-)

**Comment by DeltaQH** [comment]
When calling gnuplot from comand lind it works without problems

![image](https://user-images.githubusercontent.com/104829953/171401987-6bacdcc9-ee38-4ce0-ab9e-cfd51430b34b.png)

**Comment by volkers** [comment]
Mhm, I'm a little bit out of my wits now. You would land in the debugger if vgplot wouldn't find gnuplot, so this part seems to work.
When I test on Windows 10 it just works fine. The only difference was that I had the default terminal type "windows". But even when re-installing gnuplot with "qt" terminal it just works without problems. I have a slightly newer gnuplot though, but this should not be important.

**Comment by DeltaQH** [comment]
Thanks for your replies.

If it works for you, then there may be something strange in my windows installation.

I will try to apply the standard windows soluiton....reboot it

Best Regards

**Comment by DeltaQH** [comment]
Hi again

I was lucky enough to find the reason for the problem. Follow link below

https://stackoverflow.com/questions/67703847/gnuplot-hanging-under-windows-10

It seems there is a problem with gnuplot 5.4 and windows 10

I had version 5.4 Patchlevel 1. After installing  bersion 5.4 patchlevel 2... vgplot works on my laptop

**Note**: when installing the newer gnupro version, I selected during the installatin process to use windows as terminal. Maybe it had no effect in the resolution of the problem, but I just wanted to be on the safe side.

**Comment by DeltaQH** [comment]
Case closed :-)
